### ISSUE TITLE
Can't add integration with config flow wizard

### ISSUE THREAD

**Issue by PulsarFX** [Tasshack/dreame-vacuum#111]
**Describe the bug**
Can't add a robot because of an error message from the wizard dialog.

**To Reproduce**
Try to add the integration from the integrations list.
The wait spinner starts to show. After some time it results in this error dialog:

```
(Config flow could not be loaded)
Der Konfigurationsfluss konnte nicht geladen werden: 
<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.18.0</center> </body> </html>
```

**Expected behavior**
The wizard should start to show available options.

**Additional Information (please complete the following information)**
- HA version: 2023.3.1
- integration version: 0.16.4   179f6e1
- Model Name: dreame.vacuum.p2029

**Comment by g4challenge** [comment]
Having the same issue in comparable configuration, any workarounds?

**Comment by PulsarFX** [comment]
How is the camera involved, when the wizard should show up?
Also, Dreame F9 and L10 Pro have no camera ;-)

**Comment by PulsarFX** [comment]
I don't know what happened, today it works. 
HA is still 2023.3.1 with integration version: 0.16.4 
maybe a reboot of HA did the job already.
