### ISSUE TITLE
2FA issue

### ISSUE THREAD

**Issue by bertoo87** [Tasshack/dreame-vacuum#115]
When trying to get the integration up and running i get a message with "2FA required" and a long URL which leads to the Xiaomi website where i can request a code, paste it there and only get an "ok" as feedback. Within the integration window, nothing changes, i'm still at the login screen, and i can only press login again, which generates a new link, and by now i have to wait 24 hours before i can try again. PC and Home Assistant have the same public IP.

**Comment by bertoo87** [comment]
Hi, thanks for the quick response :)
i was able to login into Miot Auto integration (its asking for continents only compared to specific countries at the server selection), didnt ask for 2FA for whatever reason, and it also found the Robot. Basic controll is given (start, pause, return home) but no map or room selection etc).
i tried to find anything i could change in my privacy settings to never ask for 2FA again, but didnt find any option. Not in the app, not on the Mi.com Website, not even on the account.xiaomi.com

**Comment by bertoo87** [comment]
This account was created 3 days ago with email address, they don't have my phone number.

**Comment by Greenphlem** [comment]
Hi, I'm also having the same issue logging in. I get a URL , and I go to it and confirm with the code sent to my email, but the next time I try to log into the integration I get a new URL. It's a loop

**Comment by bertoo87** [comment]
> Hi, I'm also having the same issue logging in. I get a URL , and I go to it and confirm with the code sent to my email, but the next time I try to log into the integration I get a new URL. It's a loop
> 
> Edit: Update, it was my Pi-Hole. Always forget to disable when things are wonky

i dont have pi-hole, so thats not my issue here ^^

**Comment by Greenphlem** [comment]
Do you have an ad blocker? It may be interfering with something

**Comment by bertoo87** [comment]
> Do you have an ad blocker? It may be interfering with something

It really seems my custom DNS caused the Issue, or something even deeper, idk. but its working now



> If Miot works then there is nothing wrong with the account or the network connection. This issue most likely caused by my implementation of the xiaomi api.

i chose DE as server as before and it worked now after i've set my DNS to 8.8.8.8 (so standard google dns)
its working now, so i guess its not the implementation :)

Thanks to all of you guys
