### ISSUE TITLE
how can i call single room cleaning via HA?

### ISSUE THREAD

**Issue by bertoo87** [Tasshack/dreame-vacuum#118]
Since the integration is working now, i was wondering if its possible to start cleaning a particular room via HA. My goal is that i put a little button in every room, so if pressed the robot goes there and just cleans this room. The sequence cleaning mode can define a start, but after that it starts cleaning the other rooms aswell, even if not assigned a number. Is there a way to accomplish what i'm trying to do with this integration?

**Comment by bertoo87** [comment]
had some help from some1 who can actually understand machine language, its working fine now, thanks for that awesome integration 👍

**Comment by prsn85** [comment]
wow can you share the code? I love your idea for room cleaning. :)
