### ISSUE TITLE
HA reboot after add  vacuum

### ISSUE THREAD

**Issue by snatch84** [Tasshack/dreame-vacuum#193]
Home Assistant 2023.7.3
Supervisor 2023.08.1
Operating System 10.5

Vacuum L10s ultra

Dreame login pass successfully, after that, at the second submit (I left all the default selections), ha "crash" (reboot)
<img width="381" alt="image" src="https://github.com/Tasshack/dreame-vacuum/assets/36006954/0c30ac15-f7ad-4a85-b202-f021535bc43c">

After reboot, vacuum it's not present on the devices page.

Last components log before ha reboot
home-assistant.log.1:2023-08-24 23:37:40.781 DEBUG (SyncWorker_0) [custom_components.dreame_vacuum.dreame.map] Decode saved map 1: Map 1            
home-assistant.log.1:2023-08-24 23:37:40.781 INFO (SyncWorker_0) [custom_components.dreame_vacuum.dreame.map] Decode I map 1 1315                   
home-assistant.log.1:2023-08-24 23:37:40.781 DEBUG (SyncWorker_0) [custom_components.dreame_vacuum.dreame.map] Update callback                      
home-assistant.log.1:2023-08-24 23:37:40.782 DEBUG (SyncWorker_0) [custom_components.dreame_vacuum.dreame.map] Update callback                      
home-assistant.log.1:2023-08-24 23:37:40.784 DEBUG (SyncWorker_0) [custom_components.dreame_vacuum.dreame.device] Get Cleaning History
home-assistant.log.1:2023-08-24 23:37:40.832 DEBUG (SyncWorker_0) [custom_components.dreame_vacuum.dreame.device] Cleaning History Changed
home-assistant.log.1:2023-08-24 23:37:40.894 INFO (MainThread) [custom_components.dreame_vacuum] Update Host Config: None
home-assistant.log.1:2023-08-24 23:37:40.894 DEBUG (MainThread) [custom_components.dreame_vacuum] Manually updated dreame_vacuum data
home-assistant.log.1:2023-08-24 23:37:40.894 DEBUG (MainThread) [custom_components.dreame_vacuum] Finished fetching dreame_vacuum data in 2.195 seco
nds (success: True)
home-assistant.log.1:2023-08-24 23:37:41.041 DEBUG (MainThread) [custom_components.dreame_vacuum] Update map
home-assistant.log.1:2023-08-24 23:37:41.082 INFO (Thread-106 (_thread_main)) [custom_components.dreame_vacuum.dreame.device] Property STREAM_STATUS
 Added: {"operType":"end","operation":"monitor","result":0,"status":0}
home-assistant.log.1:2023-08-24 23:37:41.082 DEBUG (Thread-106 (_thread_main)) [custom_components.dreame_vacuum.dreame.device] Update Callback
home-assistant.log.1:2023-08-24 23:37:41.082 DEBUG (Thread-106 (_thread_main)) [custom_components.dreame_vacuum] Manually updated dreame_vacuum data
home-assistant.log.1:2023-08-24 23:37:41.348 DEBUG (MainThread) [custom_components.dreame_vacuum.dreame.map] Render MATERIAL
home-assistant.log.1:2023-08-24 23:37:41.350 DEBUG (MainThread) [custom_components.dreame_vacuum.dreame.map] Render CARPET
home-assistant.log.1:2023-08-24 23:37:41.532 DEBUG (MainThread) [custom_components.dreame_vacuum.dreame.map] Render PATH

**Comment by snakedm** [comment]
Same problem here.

On secund try, I was able to add the device. But, after that my HA entrys in reboot loop mode.

**Comment by snakedm** [comment]
> Map feature uses a lot of ram to preseve some cpu while rendering the image because of that integration cannot be used on devices like RPI3/4 with < 2GB ram.
> I have added the `Low Resolution Map` option for this reason and it should solve your problem.

But I use HA with unRAID on my server with dedicated 16GBs.

**Comment by snakedm** [comment]
> > > Map feature uses a lot of ram to preseve some cpu while rendering the image because of that integration cannot be used on devices like RPI3/4 with < 2GB ram.
> > > I have added the `Low Resolution Map` option for this reason and it should solve your problem.
> > 
> > But I use HA with unRAID on my server with dedicated 16GBs.
> 
> That means this a different issue and i need to reproduce it on my system to fix it.


Update: I confirm that's an RAM issue. After all, in this moment I only have 2GB dedicated to HA and he entry in reboot loop. 
If I activate Low Resolution Map, HA don't restart anymore.

**Comment by snatch84** [comment]
I also confirm that is RAM issue (i add some ram on virtualbox configuration).
Now i see my vacuum on devices list ;)
thansk
