### ISSUE TITLE
Can't login via Dreame account 

### ISSUE THREAD

**Issue by Ontry57** [Tasshack/dreame-vacuum#240]
**Describe the bug**
I'm trying to use DreameAccount instead of Xiaomi Account a

**To Reproduce**
Add integration -> login 

**Expected behavior**
Error -> Check your login 

**Screenshots**

![IMG_5830](https://github.com/Tasshack/dreame-vacuum/assets/67488169/206931d3-bff0-430d-b805-1907eee5f6d0)

**Additional Information (please complete the following information)**
 - L10ultra

**Comment by fusionstream** [comment]
Just adding on here that possibly the account has not been created? Because I can't login to mine either. Even using the extractor produces no results.
