### ISSUE TITLE
Dreame has its own app and is no longer with Xiaomi

### ISSUE THREAD

**Issue by maxlin1** [Tasshack/dreame-vacuum#334]
Hi, 
Dreame has its own app and is no longer with Xiaomi, Hi I wanted to add the plugin. However, I cannot log in with the credentials because I need a Xaomi cloud here. I have also created an account there but the robot does not appear. I googled something. Dreame has its own app. So it probably doesn't work anymore. Does anyone have an idea or can help me?

Thanks Max

**Comment by tobycth3** [comment]
Same issue here, just purchased a Dreame and unable to log in to this integration

**Comment by maxlin1** [comment]
Perfekt I use v 2.0.0b9 it works with a dream Account

**Comment by mark007** [comment]
With the latest beta, and an L20 Ultra I cannot get the integration to connect with either my Xiaomi cloud or dreame.com user/password. It says not authenticated. Is there a very specific website credentials we should use instead of the dreame.com email/password combination.
