### ISSUE TITLE
Problem in access

### ISSUE THREAD

**Issue by Fallegro** [Tasshack/dreame-vacuum#339]
Hi team,

i try to activate this integration, but afther the log in i received this error:
"No supported device was found in this Xiaomi Miio Cloud account in the selected location."
come can I solve the problem?
I tried with all the servers in the list but nothing

**Comment by M4v3r1cK87** [comment]
I have this problem too

**Comment by Fallegro** [comment]
i have a Dreame L10S

**Comment by llerch** [comment]
I get the same error message with my dreame l10s ultra. Are there any fixes?

**Comment by Fallegro** [comment]
@Tasshack i and @llerch have a dreame l10s ultra but this noi working can you help?
