### ISSUE TITLE
Integration start failed: Traceback

### ISSUE THREAD

**Issue by cookie2512** [Tasshack/dreame-vacuum#370]
**Describe the bug**
The Integration was running the past month without any issue. Didn't update Home Assistant and the integration is up to date. 

**Log**
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.dreame_vacuum
Source: custom_components/dreame_vacuum/coordinator.py:496
Integration: Dreame Vacuum (documentation, issues)
First occurred: 15. Januar 2024 um 18:08:02 (1933 occurrences)
Last logged: 17:06:30

Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 491, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2385, in update raise DeviceUpdateFailedException("Device cannot be reached") from None custom_components.dreame_vacuum.dreame.exceptions.DeviceUpdateFailedException: Device cannot be reached
Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 491, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2382, in update self.connect_device() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1760, in connect_device self._request_properties() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 559, in _request_properties result = self._protocol.get_properties(props[:15]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1319, in get_properties return self.send( ^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1307, in send raise DeviceException( custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud

**Additional Information (please complete the following information)**
 - Model Name: Dreame L10s Ultra
 - Firmware Version [e.g. 1156]: 4.3.9_3104
 - Home Assistant Version: 2023.12.1
 - Configuration Type [With or without map support]: with map
 - Errors or warnings shown in the HA logs (if applicable):

**Comment by c-artner** [comment]
Same here:

2024-01-25 06:26:20.800 WARNING (MainThread) [custom_components.dreame_vacuum] Integration start failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 326, in _async_update_data
    await self.hass.async_add_executor_job(self.device.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 996, in update
    self.connect_device()
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 725, in connect_device
    self.info = DreameVacuumDeviceInfo(self._protocol.connect())
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 495, in connect
    response = self.send("miIO.info", retry_count=retry_count)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 536, in send
    return self.device.send(method, parameters=parameters, retry_count=retry_count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.0.12

**Additional Information (please complete the following information)**

Model Name: Dreame L10s Ultra
Firmware Version [e.g. 1156]: 4.3.3_1210
Home Assistant Version: 2024.1.5
Integration Version: v1.0.2
Configuration Type [With or without map support]: with map

**Comment by bnystrom** [comment]
Same

**Comment by cookie2512** [comment]
Still got the issue... But I become all the notifications in home assistant. Clean up complete, robot stuck, detergent empty, water empty, etc.

**Comment by cookie2512** [comment]
i solved the problem
i looked in the /etc/resolv.conf file and the nameserver was mit my router. i changed it to "nameserver 8.8.8.8", reboot my server and the issue was solved.
