### ISSUE TITLE
Custom cleaning with  Dreame L10 Prime

### ISSUE THREAD

**Issue by Tasshack** [Tasshack/dreame-vacuum#381]
### Discussed in https://github.com/Tasshack/dreame-vacuum/discussions/380

<div type='discussions-op-text'>

<sup>Originally posted by **calcioscacchi** January 28, 2024</sup>
Hi there. 

I've integrated the robot with success via beta 2.0.0b11 version.
I'm trying to set 2 custom cleaning automations for each room, one is just for sweeping, one is for sweeping and mopping. 

In order to do this, I've tried building a script to call with Alexa, the script is a call to "dreame_vacuum.vacuum_set_custom_cleaning" service.

This is the code for the sweeping one:

`service: dreame_vacuum.vacuum_set_custom_cleaning
target:
  entity_id: vacuum.battista
data:
  segment_id:
    - 7
  suction_level:
    - 2
  repeats:
    - 1
  water_volume:
    - 1
`

The problem is that HomeAssistant gives me the following error: 

"Cannot edit customized cleaning parameters on current map".
Any idea to fix this problem?

Thanks.

</div>

**Comment by calcioscacchi** [comment]
> @calcioscacchi I have checked the code and it seems this is a bug in the `vacuum_set_custom_cleaning` service. I will fix this on the next beta release, you can downgrade to `v2.0.0.b9` until then.

Thanks for your work. 
Is the update scheduled or is classified as ASAP? :P

**Comment by calcioscacchi** [comment]
> > > @calcioscacchi I have checked the code and it seems this is a bug in the `vacuum_set_custom_cleaning` service. I will fix this on the next beta release, you can downgrade to `v2.0.0.b9` until then.
> > 
> > 
> > Thanks for your work. Is the update scheduled or is classified as ASAP? :P
> 
> There are no relevant updates/fixes between `b9` and `b11` about L10 Prime so there won't be any difference for you after downgrading it.

HA says that I must downgrade using the service (choosing older versions than the last one avaiable is no longer possible). I need the SHA code of the commit. If the commit SHA code is this:

06875eb1dcb390f4f3c10555920f4e0d72066d99

Then HA says that an unknown error doesn't allow the update. Is the SHA correct?
![image](https://github.com/Tasshack/dreame-vacuum/assets/60674280/2028512a-d1bd-4da7-8344-d12d16b3a6c9)

**Comment by calcioscacchi** [comment]
I do. But HA does'nt allow me to select the b9 and force the selection on the b11

![image](https://github.com/Tasshack/dreame-vacuum/assets/60674280/f9e12211-3e6d-416d-8eee-125059525b88)

**Comment by calcioscacchi** [comment]
Ok I did it. The problem was that in this page HA suggest to use the full SHA in the "version" field. But it works great putting "v2.0.0b9" instead.

https://experimental.hacs.xyz/docs/entities/update_entities/#install-service

**Comment by calcioscacchi** [comment]
In the version b9, it says the I have a parameter count mismatch error:

![image](https://github.com/Tasshack/dreame-vacuum/assets/60674280/fbb374b3-450a-4545-a87a-65fe5ff6a6d6)

**Comment by calcioscacchi** [comment]
> I forgot that I have fixed that too in b11, so i guess you have to wait to the new release.

Ok, can't wait for it. It is supposed to be published soon?


Anyway, If i run the custom cleaning service, it just set a cleaning mode (so I need another command to start cleaning) or my robot will start cleaning with the custom configuration setted in the script?

**Comment by calcioscacchi** [comment]
> It would be a viable option but you need to disable the `customized_cleaning` switch otherwise robot will ignore the parameters you have passed to the service.

This means that I need to build an automation with 3 steps: 1) configuration 2)disable the customized_cleaning 3)start cleaning. 
Did I get it?
