### ISSUE TITLE
 Invalid "sensors must be cleaned warning"

### ISSUE THREAD

**Issue by davidbeijinho** [Tasshack/dreame-vacuum#399]
**Describe the bug**
similar to https://github.com/Tasshack/dreame-vacuum/issues/311 i got a notification, but in the app this option is not available

**To Reproduce**
after a clean i got a notification

**Expected behavior**
this notification should not be visible

**Screenshots**
![notification](https://github.com/Tasshack/dreame-vacuum/assets/2984693/8c37c597-82eb-4e33-8871-646232df2c69)
![image](https://github.com/Tasshack/dreame-vacuum/assets/2984693/6ebe31a3-8cd8-418c-b54d-ce1f49917f50)

**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.p2027
 - Firmware Version: 4.1.8_1094
 - Home Assistant Version: 2024.1.6
 - Configuration Type [With or without map support]: with map
 - Errors or warnings shown in the HA logs (if applicable):

**Comment by davidbeijinho** [comment]
Dreame Bot W10

**Comment by davidbeijinho** [comment]
found it, thanks

**Comment by Majestic7979** [comment]
I also have the same, I was just using the service call to reset the sensor... and it resets it as expected. So this functionality is actually exposed in the firmware, but it's not in the app for some reason.

**Comment by Majestic7979** [comment]
That's interesting to know, I like to know background info like that, very useful!! Thanks

**Comment by Majestic7979** [comment]
> Also all of the European models (called L series) are actually the Chinese models of previous year. I know this because there are no L series in the code, only S and X series are present and L series are actually the combination of S models with X docks and vice versa. So when you buy a European model from EU, it is much likely that it is already EOL or very close to it. Also every hardware they made actually has two models, one for EU/US and one for the CN market but they are exactly the same hardware/software with the exception of a region lock. Model numbers and names not related of those devices for make it harder for consumer to compare them in the market.

Manufacturers are crazy. I suppose that they are using their Chinese customers as beta testers first, and if all goes well then they release to other regions. We don't get the W10 in the UK, so I imported mine from Germany. It's a great robot, it does a decent job of cleaning three types of different floors with no change required from me. Pretty much the only "issue" I have with it now is unable to reset the sensors from their app... It's really cool of you to share your knowledge like that, did you consider putting it in the Wiki or readme if not there already? I'm a geek so I love reading stuff like this :)

**Comment by Majestic7979** [comment]
Thank you man!!
