### ISSUE TITLE
dreame.vacuum.r9316h

### ISSUE THREAD

**Issue by Tasshack** [Tasshack/dreame-vacuum#435]
### Discussed in https://github.com/Tasshack/dreame-vacuum/discussions/433

<div type='discussions-op-text'>

<sup>Originally posted by **JonathanTung1981** February 28, 2024</sup>
Any chances to support new model dream.vacuum.r9316h in the feature ?

thanks</div>

**Comment by WHQJonathan** [comment]
Thank you

**Comment by JonathanTung1981** [comment]
By the way when I try login Dreamehome  account got "Could not login, check the credentials." Dose it correct ? I can login Dreamehome app 
thank you

**Comment by dsyff** [comment]
I'd love to have this supported too!! Thank you!

**Comment by dsyff** [comment]
Not sure what the difference is but mine shows up as r9316k instead of r9316h

**Comment by WHQJonathan** [comment]
> Not sure what the difference is but mine shows up as r9316k instead of r9316h

Hope all can be supported  ^^
