### ISSUE TITLE
Sweep/Mop Mode in Customized Cleaning

### ISSUE THREAD

**Issue by luisiam** [Tasshack/dreame-vacuum#44]
I have the DreameBot L10s Ultra and I am really enjoying this integration. However, I don't find a way to set the sweep/mop mode with the `vacuum_set_custom_cleaning` service. I can only control the suction, water, and repeat. Am I missing something?

**Comment by luisiam** [comment]
Thanks. It works like a charm!

**Comment by tankcom** [comment]
> * Cleaning Mode: [1,2,1,2,**X**] 0: Sweeping, 1: Sweeping and Mopping, 2: Mopping

1 and 2 are mixed up here,

1 is only mopping, 2 is sweeping and mopping for me (L10s ultra)

**Comment by tankcom** [comment]
> Related to #66

Is this already integrated so I don't have to use the send_command workaround? I couldn’t find it last time I checked.

**Comment by bankir82** [comment]
> Setting custom cleaning mode for rooms are introduced on this years models and not available on older devices therefore it is not available on this integration too. I am going to add this feature on a future release but until then you can use `send_command` service like this for updating the cleaning mode.
> 
> ```
> service: vacuum.send_command
> data:
>   command: action
>   params:
>     did: "6.2"
>     siid: 6
>     aiid: 2
>     in:
>       - piid: 4
>         value: "{\"customeClean\":[[4,2,2,2,0],[5,0,2,3,1],[3,3,2,2,1],[2,2,4,1,0],[1,3,2,2,2]]}"
> target:
>   entity_id: vacuum.vacuum
> ```
> 
> * Value needs to be string json and must not contain spaces
> * Array must contain all rooms on the current map
> * Array parameters must include all available settings
> * Array parameters
>   
>   * Room ID: [**X**,2,1,2,0]
>   * Suction Level: [1,**X**,1,2,0] 0: Quiet, 1: Standard, 2: Strong, 3: Turbo
>   * Water Volume: [1,2,**X**,2,0] 2: Low, 3: Medium, 4:High
>   * Repeats: [1,2,1,**X**,0] 1,2,3
>   * Cleaning Mode: [1,2,1,2,**X**] 0: Sweeping, 1: Mopping, 2: Sweeping and Mopping

Its worked, tnks )))
xiaomi omni 1s

**Comment by Friedi1970** [comment]
>  * Value needs to be string json and must not contain spaces
> * Array must contain all rooms on the current map
> * Array parameters must include all available settings
> * Array parameters
>   
>   * Room ID: [**X**,2,1,2,0]
>   * Suction Level: [1,**X**,1,2,0] 0: Quiet, 1: Standard, 2: Strong, 3: Turbo
>   * Water Volume: [1,2,**X**,2,0] 2: Low, 3: Medium, 4:High
>   * Repeats: [1,2,1,**X**,0] 1,2,3
>   * Cleaning Mode: [1,2,1,2,**X**] 0: Sweeping, 1: Mopping, 2: Sweeping and Mopping

Hi again. What I really don‘t understand is the cleaning mode. The last number is the cleaning mode, right? Within the HA integration it is not possible to set the cleaning mode individually for each room.
My question now is: is it really possible to select different modes using this way? And did I understand right that the settings must be done for every room on the map, even if they shall not be leaned because e.g. the doors are closed?
