### ISSUE TITLE
Dreame D10s support?

### ISSUE THREAD

**Issue by TheIceMagmaCube** [Tasshack/dreame-vacuum#457]
Hi there,
Does the project has support for the D10s model?

It seems quite new and they're not a lot of informations about it.

**Comment by TheIceMagmaCube** [comment]
Found my anwser. Thanks y'all for your work!

**Comment by andmadeira** [comment]
Hi @TheIceMagmaCube! Can you please share the answer you found?

**Comment by TheIceMagmaCube** [comment]
Hey,
By looking deeper in the issues, the D10s appears to be supported in the beta version.
Check the latest beta branch on git and it should be in the supported devices.

Have a great day!
