### ISSUE TITLE
Latest update Integration start failed

### ISSUE THREAD

**Issue by robitsrl** [Tasshack/dreame-vacuum#491]
**Describe the bug**
I have updated with the latest version and the integration failed to start. On frontend I have the following error:

invalid calibration, please check configuration

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

Everythings working 

**Screenshots**
![dreame](https://github.com/Tasshack/dreame-vacuum/assets/43490239/bf5adf70-7117-4410-a4e5-07a80b92ff9b)

**Additional Information (please complete the following information)**
 - Model Name L10s Ultra
 - Firmware Version [e.g. 4.3.9_3204]:
 - Home Assistant Version: 
 - Configuration Type [With map support]:
 - Errors or warnings shown in the HA logs (if applicable):
 - 
Integration start failed: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 193, in send data, addr = s.recvfrom(4096) ^^^^^^^^^^^^^^^^ TimeoutError: timed out During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 193, in send data, addr = s.recvfrom(4096) ^^^^^^^^^^^^^^^^ TimeoutError: timed out The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 326, in _async_update_data await self.hass.async_add_executor_job(self.device.update) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 996, in update self.connect_device() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 733, in connect_device self._request_properties() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 262, in _request_properties result = self._protocol.get_properties(props[:15]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 543, in get_properties return self.send("get_properties", parameters=parameters, retry_count=retry_count) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 536, in send return self.device.send(method, parameters=parameters, retry_count=retry_count) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 233, in send return self.send( ^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 241, in send raise DeviceException("No response from the device") from ex miio.exceptions.DeviceException: No response from the device

**Comment by Jack77777777** [comment]
@robitsrl I have the same issue. How did you fix it ?

**Comment by robitsrl** [comment]
fixed by it self

**Comment by Jack77777777** [comment]
For me it was resolved after some minutes by itself too. But after a restart occured again. Plus my room coordinates (multi floor) where shifted when changing floor. 

The fix is https://github.com/Tasshack/dreame-vacuum/pull/805
