### ISSUE TITLE
L20 Ultra mop not possible when left in station

### ISSUE THREAD

**Issue by Tasshack** [Tasshack/dreame-vacuum#517]
<sup>Originally posted by **Jack77777777** April 28, 2024</sup>
I set in Dreame App to leave the mops in the base when only sweeping.
After after that i can not select mop or sweep/mop. Is there a way to achieve this with your integration or a button/service to install the mops through or is the only way to deactivate this function in the Dreame app and let the robot lift the mops when only sweeping ?? 

  </div>

**Comment by Jack77777777** [comment]
@Tasshack thank you for replying. Screenshot of what do you need?

**Comment by Jack77777777** [comment]
@Tasshack thank you for taking care. As you mentioned "when mops are left in base and robot is kot docked". I meant when the robot is docked, sleeping and the mops are deassembled and lying in the base.

**Comment by Jack77777777** [comment]
@Tasshack i don't know if it helps but here are pictures from Dreamehome and Home Assistant with mops left in dock and vacuum docked. You can see in Dreamehome i can change the mode, in HA ich have only sweep as option. ![image](https://github.com/Tasshack/dreame-vacuum/assets/64719909/c12001dc-d973-438f-a89c-31566d71185f)
![image](https://github.com/Tasshack/dreame-vacuum/assets/64719909/39831ae6-8066-4166-b68f-6ba6ee3320be)
![image](https://github.com/Tasshack/dreame-vacuum/assets/64719909/2c24bdc8-a358-4108-be7c-4c8bd3345c35)
![image](https://github.com/Tasshack/dreame-vacuum/assets/64719909/043d1b84-a528-4fea-bc58-df37921a8ef7)
