### ISSUE TITLE
Failed to call the service

### ISSUE THREAD

**Issue by Filipe-PT** [Tasshack/dreame-vacuum#535]
**Describe the bug**
Hello . Right now I can't call any service other than locate . This is the only one that is working, all the others (start, stop, pause, return to base, etc etc ) are failing when calling the service.

**Screenshots**
![Captura de ecrã 2024-05-08 231527](https://github.com/Tasshack/dreame-vacuum/assets/108993517/d160d47a-ad3c-46ca-b272-f8a08efe6ac3)
![Captura de ecrã 2024-05-08 231704](https://github.com/Tasshack/dreame-vacuum/assets/108993517/f1e924f1-0609-4b08-92b0-dafd3cbdc544)
![Captura de ecrã 2024-05-08 231743](https://github.com/Tasshack/dreame-vacuum/assets/108993517/7ffce71d-b8cd-42f4-8437-00f6f215c47c)
![Captura de ecrã 2024-05-08 233506](https://github.com/Tasshack/dreame-vacuum/assets/108993517/866f7013-8426-4bdb-875d-8175350733c4)

**Additional Information (please complete the following information)**
 - Model Name : dreame.vacuum.p2009
 - Firmware Version :  4.1.8_1132
 - Home Assistant Version: 
  * Core 2024.5.2
  * Supervisor 2024.05.1
  * Operating System 12.3

![Captura de ecrã 2024-05-08 231747](https://github.com/Tasshack/dreame-vacuum/assets/108993517/65b279fd-f43e-4a02-bcd8-c043c40f075c)

   
 - Configuration Type [With or without map support]: With map support

**Comment by mifraburneo** [comment]
#523

**Comment by Filipe-PT** [comment]
Thank you very much, it now works.
