### ISSUE TITLE
Integration doesn't work

### ISSUE THREAD

**Issue by Foxinbox375** [Tasshack/dreame-vacuum#582]
Not a single function works except for searching for a vacuum cleaner.
After pressing the buttons an error is displayed, screenshot below...
![image](https://github.com/Tasshack/dreame-vacuum/assets/124099364/fdba807c-c41e-4ffa-8d85-99705726034b)

**Comment by Hoekeren** [comment]
Same

**Comment by IceBotYT** [comment]
Seems to be a dupe of #581
