### ISSUE TITLE
Xiaomi X10+ randomly changes cleaning mode to sweeping 

### ISSUE THREAD

**Issue by joserzc** [Tasshack/dreame-vacuum#585]
**Describe the bug**
The entity randomly changes cleaning mode from sweeping and mopping to sweeping.

**To Reproduce**
Not sure when this happens. It's kind of random, haven't noticed any pattern yet. If it helps, it cleans my house 3 times a week. The automation is made in Mi home app

**Expected behavior**
Cleaning mode should be the same unless I explicitly decide to change it.

**Screenshots**
![Screenshot_2024-06-10-09-05-57-090_io homeassistant companion android](https://github.com/Tasshack/dreame-vacuum/assets/15677054/b29425b6-8e2d-4ea7-915f-ac314c3ee39e)
It was changed at 4:22 am. Of course I was not using it then. It looks like it can be related to some entities becoming unavailable.

**Additional Information (please complete the following information)**
 - Model Name: dreame.vacuum.p2114a
 - Firmware Version [e.g. 1156]: 4.3.3_1504
 - Home Assistant Version: Home Assistant OS 12.3. Core 2024.6.1
 - Configuration Type [With or without map support]: With map support
 - Errors or warnings shown in the HA logs (if applicable): None

**Comment by welderpb** [comment]
Still have this issue with x10+ on latest version
![image](https://github.com/user-attachments/assets/25bba899-d571-4001-8247-4dce67c71c72)



When cleaning is completed (in random time) "Cleaning mode" return to "Swepping"

![image](https://github.com/user-attachments/assets/341e5988-98ec-441d-8625-e74ffee8b74e)

**Comment by welderpb** [comment]
> That is not your currently installed version indicator but the latest released version.

![image](https://github.com/user-attachments/assets/62698824-d077-4683-98b7-e4341f0881aa)
This indicator show me "version downloaded"
