### ISSUE TITLE
Problem with L10S with water tank state

### ISSUE THREAD

**Issue by Tasshack** [Tasshack/dreame-vacuum#63]
@argonaute199 Said:
I tried the integration with my Dream L10S. Everything works excepted the sweeping. I can only use the mopping and when I try to change, I get a service call failure "water tank not installed".
The water tank entity has been created, but its state is always "unknown". So the issue is there.

Of course, I check the vacuum and the water tank is correctly installed. I can activate the sweeping mode with the xiaomi app. And I cannot enymore if I remove the water tank : the Xiaomi app detects correctly the water tank.

What can I do ? Thank you.

**Comment by argonaute199** [comment]
Hi,

Find enclosed the log with info level. There is no error for dreem_vacuum.

Kind regards.

Patrick

 

De : Tasshack ***@***.***> 
Envoyé : samedi 17 décembre 2022 05:55
À : Tasshack/dreame-vacuum ***@***.***>
Cc : Argonaute ***@***.***>; Mention ***@***.***>
Objet : Re: [Tasshack/dreame-vacuum] Problem with L10S with water tank state (Issue #63)

 

@argonaute199 <https://github.com/argonaute199>  Can you update the log level to info and send the full log output after the HA starts?

logger:
  logs:
    custom_components.dreame_vacuum: info

**Comment by argonaute199** [comment]
Oh great, thank you very much.
I replied with the mail, and the attached file has not been relayed to github. Sorry for this, and let me know if you need it.

So I tested : 
-	The water tank has now the status “installed” (ok)
-	I can change cleaning mode (ok)
BUT the modes are not good and swapped.

Mode in Home Assistant addon   =>  mode in the Xiaomi App :
-	Sweeping => Sweeping & mopping (washing with succion)
-	Mopping => Sweeping (washing only)
-	Sweeping & mopping =>  sweeping (suction only)
