### ISSUE TITLE
⚠️NEED ACCESS TO X40 ULTRA 🙏

### ISSUE THREAD

**Issue by Tasshack** [Tasshack/dreame-vacuum#662]
I need access to a X40 series device to be able to fully support it's new features.

https://github.com/Tasshack/dreame-vacuum/issues/646
https://github.com/Tasshack/dreame-vacuum/issues/633

**Comment by tioan** [comment]
Do you need physical on-site access to an X40 or is remote access to Homeassistant + Dream app access sufficient?

**Comment by tioan** [comment]
I would be happy to share my X4p Ultra Complete + fixed water connection kit with you for a few days, for which I would need your Dream ID

**Comment by apocaliss92** [comment]
Let me know if you still need a device

**Comment by apocaliss92** [comment]
Thank you very much! Could you also give a check if a polling behavior is required? Looks like when the water tank is empty, the mobile app asks the status to the vacuum to check if it changed, the only workaround on ha is to reload the integration

Thanks again, I can empty the tanks if you need :)

**Comment by apocaliss92** [comment]
> Also I am sure this is not the latest fimware for this device yet because I can see much more settings are available from the app source code but currently disabled. So more features will be added to this device following months to the app when the new firmware is released.

This looks an awesome news :D

**Comment by apocaliss92** [comment]
> > Thank you very much! Could you also give a check if a polling behavior is required? Looks like when the water tank is empty, the mobile app asks the status to the vacuum to check if it changed, the only workaround on ha is to reload the integration
> > Thanks again, I can empty the tanks if you need :)
> 
> I think the issue is, when you dismiss the warning from the app it also clears the warning from the device but the cloud does not notice the integration about the change so it will became permanently stuck on the integration because there is no way to integration to know that is has been cleared otherwise.
> 
> I am not sure how to solve this yet because it is tricky without having a device always runs out of water that I can access to. Can you enable the `info` logs, create a low water situation, repeat the same steps from the app and send me the log output?
> 
> ```
> logger:
>   default: warn
>   logs:
>     custom_components.dreame_vacuum: info
> ```

I will in around 2 hours as soon as I'm back home and post here again

**Comment by apocaliss92** [comment]
Hey @Tasshack, I found some time to go through this. This is what I have done

1. I Clean water tank completely removed (clean-water-tank-not-installed.log](https://github.com/user-attachments/files/16622151/clean-water-tank-not-installed.log)

2. Clean water tank inserted as empty ([clean-water-tank-installed-empty.log](https://github.com/user-attachments/files/16622156/clean-water-tank-installed-empty.log)

3. Clean water tank filled with water at maximum 
  - Log without restarting 
[clean-water-tank-installed-full.log](https://github.com/user-attachments/files/16622174/clean-water-tank-installed-full.log)
- Logs right after restart [clean-water-tank-not-installed-restart.log](https://github.com/user-attachments/files/16622189/clean-water-tank-not-installed-restart.log)

During all these steps, I kept the mobile app open, every single passage was reflecting in the mobile app after 1-2 seconds (polling?). The HA integration did not notice any change during these steps
![image](https://github.com/user-attachments/assets/47a0e621-90c3-4c29-9c87-4da27276067f)

Please let me know if I can help further on this or pick logs in a different order. Just to be sure, I did not touch any notification in the mobile app or on ha, just removed, refilled and so on, no direct interaction with both HA and app

**Comment by apocaliss92** [comment]
Later today I will try to do the same with the dirty water tank, I suspect it's exactly the same behavior, the sensors inside the tanks are the same, 1 for the actualy installation and 1 to check the water level

**Comment by Kolia56** [comment]
If needed I can share my device too. 4 maps are configured and the auto refilling / drainage kit is installed. BTW is this option currently supported in b16 version?

**Comment by JanKraslice** [comment]
Hi v2.0.0b16 contains the additions mentioned in #646 ? 
Thank you

**Comment by apocaliss92** [comment]
@Tasshack i just encountered a low detergent case, here is a fresh log while it's shown on the app
[Low detergent.log](https://github.com/user-attachments/files/16787419/Low.detergent.log)

**Comment by apocaliss92** [comment]
@Tasshack let me know if you need access to an X50 now :)

**Comment by apocaliss92** [comment]
Done!

**Comment by Tasshack** [comment]
@apocaliss92 I guess you have hard reset your device because I no longer have access to it but sharing message still says accepted.

**Comment by Tasshack** [comment]
BP428398, Thanks!
