### ISSUE TITLE
Support For Xiaomi Robot Vacuum S20 EU -  xiaomi.vacuum.d106gl

### ISSUE THREAD

**Issue by Rakura-cloud** [Tasshack/dreame-vacuum#669]
Hi,

Is it possible to add support for the Xiaomi Robot Vacuum S20 EU (xiaomi.vacuum.d106gl)? I can provide additional information about the device. I was able to add the string {xiaomi.vacuum.d106gl} to config_flow.py, but I cannot retrieve any other data from the vacuum.

![Screenshot 2024-08-15 at 17 42 19](https://github.com/user-attachments/assets/41bd5bd9-7bcf-4eac-b038-abd8470422b8)

I have also enabled debug logging.

[home-assistant_dreame_vacuum_2024-08-15T15-33-53.780Z.log](https://github.com/user-attachments/files/16627038/home-assistant_dreame_vacuum_2024-08-15T15-33-53.780Z.log)

Thanks for your support and hard work.

**Comment by Rakura-cloud** [comment]
I see, its now working using official HA Xiaomi integration. Thanks for your time. Have a nice day.

**Comment by powas** [comment]
@Rakura-cloud did you get it to work? I could´t find it with the Xiaomi integration.

**Comment by Rakura-cloud** [comment]
@powas 
Hi,
I have a issues with that integration, but I used the Xiaomi Miot Auto integration in HACS [from this link](https://github.com/al-one/hass-xiaomi-miot). It doesn't have all the features, but at least I can turn on the vacuum, stop it, and return it to the dock. The picture below shows the available entries. I hope my advice will be useful to you.
![Screenshot 2024-09-05 at 00 42 32](https://github.com/user-attachments/assets/7297e739-9044-4471-960d-6c26de96e87b)

**Comment by powas** [comment]
@Rakura-cloud Awesome, thank you!!!
