### ISSUE TITLE
Need access at component

### ISSUE THREAD

**Issue by Bobsilvio** [Tasshack/dreame-vacuum#676]
<img width="529" alt="Screenshot 2024-08-20 alle 12 00 35" src="https://github.com/user-attachments/assets/a489a3e7-a598-4460-bbc8-9c43e9982193">
I can't log in, either with email or with the username I find on the APP

**Comment by Bobsilvio** [comment]
Is a Dreame x40 ultra

**Comment by tioan** [comment]
I use an X40 Ultra with the Dreame app and ‘Dreamehome Account’ without any problems, have you tested this?
