### ISSUE TITLE
Dreame X30 Pro Single Room Cleaning 

### ISSUE THREAD

**Issue by JonasH93Dev** [Tasshack/dreame-vacuum#792]
Hi
I`m using a Dreame X30 Pro.
I cant find an option where i can only clean a single room. Also the roomcleaning via map isnt working i can select the room but the map sais cant connect to cloud
![Bild1](https://github.com/user-attachments/assets/ace3b8fb-0cc7-433f-beda-06e67abb663d)

**Comment by Haenk93** [comment]
But I dont know what I did wrong I read the docs
