### ISSUE TITLE
DeviceUpdateFailedException("Device cannot be reached")

### ISSUE THREAD

**Issue by hooker78** [Tasshack/dreame-vacuum#831]
**Describe the bug**
After upgrade to python 3.12.7 and  HA 2024.12.1 I can not connect anymore to my device (LS10s Pro Ultra Heat). I am using version v2.0.0b16 of the integration. I have deleted the instance and recreated it, using dreame-cloud login euope. Login works, but then I get the error " Failed setup, will retry: Device cannot be reached"

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]:
LS10s Pro Ultra Heat dreame.vacuum.r2216o

 - Home Assistant Version: 
 2024.12.1

 - Configuration Type [With or without map support]:
  with map

 -Error Log
```

Logger: custom_components.dreame_vacuum
Source: custom_components/dreame_vacuum/coordinator.py:443
integration: Dreame Vacuum ([documentation](https://github.com/Tasshack/dreame-vacuum), [issues](https://github.com/Tasshack/dreame-vacuum/issues))
First occurred: 2:20:54 PM (11 occurrences)
Last logged: 2:27:49 PM
Integration start failed: Traceback (most recent call last): File "/home/homeassistant/.homeassistant/custom_components/dreame_vacuum/coordinator.py", line 437, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/homeassistant/.homeassistant/custom_components/dreame_vacuum/dreame/device.py", line 2815, in update raise DeviceUpdateFailedException("Device cannot be reached") from None custom_components.dreame_vacuum.dreame.exceptions.DeviceUpdateFailedException: Device cannot be reached
```

**Comment by hooker78** [comment]
fair enough - it was worth the try.

**Comment by filmackay** [comment]
Is a changing local/private IP one of these reasons, by any chance? Or does it only ever communicate via cloud?

OOI why would Google DNS help - are there issues with DNS replication of Dreame-related domains?

**Comment by jeremyjoslin** [comment]
Same problem. Using NextDNS. No blocked DNS queries. Nothing on Firewall that's blocking traffic. Works locally with app, but getting same error: Failed setup, will retry: Device cannot be reached

This just started after working fine for months. I did change out wireless access points which required some config updates on the device, but even after deleting integration and adding from scratch I still get this.

**Comment by jeremyjoslin** [comment]
Not sure if meaningful, but my iOS app is making calls to 10000.mt.us.iot.dreame.tech
Meanwhile HAOS is making calls to us.iot.dreame.tech

**Comment by YBonline** [comment]
I just had this issue start after upgrading to HA 2025.3


`Logger: custom_components.dreame_vacuum
Source: custom_components/dreame_vacuum/coordinator.py:443
integration: Dreame Vacuum ([documentation](https://github.com/Tasshack/dreame-vacuum), [issues](https://github.com/Tasshack/dreame-vacuum/issues))
First occurred: 12:28:16 PM (389 occurrences)
Last logged: 2:13:20 PM

Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 437, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2815, in update raise DeviceUpdateFailedException("Device cannot be reached") from None custom_components.dreame_vacuum.dreame.exceptions.DeviceUpdateFailedException: Device cannot be reached
Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 437, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2812, in update self.connect_device() ~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2038, in connect_device self._request_properties() ~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 695, in _request_properties result = self._protocol.get_properties(props[:15]) File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1241, in get_properties return self.send("get_properties", parameters=parameters, retry_count=retry_count) ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1233, in send raise DeviceException("Unable to discover the device over cloud") from None custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud`

**Comment by xaralis** [comment]
Upon upgrading to 2025.3, I'm having exactly the same issue. It was working fine beforehand, must be related.

**Comment by skybarberom** [comment]
Same here after updating to 2025.3.

`2025-03-07 14:53:40.436 WARNING (MainThread) [custom_components.dreame_vacuum] Integration start failed: Traceback (most recent call last):
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 437, in _async_update_data
    await self.hass.async_add_executor_job(self._device.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2815, in update
    raise DeviceUpdateFailedException("Device cannot be reached") from None
custom_components.dreame_vacuum.dreame.exceptions.DeviceUpdateFailedException: Device cannot be reached`

**Comment by elliottmarter** [comment]
Also getting the same issue and on 2025.3 too

**Comment by elliottmarter** [comment]
Ignore my above comment, if anyone else stumbles across this thread and not the main one.

tl:dr open HACS and re-download the addon and select v2.0.0b17 (or greater)

**Comment by Rodrigolmti** [comment]
Hello, a complement on elliottmarter comment. Version v2.0.0b17 indeed fixes the issue, but with you have the integration installed I recommend you do the following:

1. Remove the integration;
2. Restart HA;
3. Install the integration, and select the latest version or above (v2.0.0b17);
4. Restart HA;

Then start the configuration for the integration. Without the restarts in between, even selecting v2.0.0b17 it was installing v2.0.0b16.

Now the issue can be properly closed since we have a solution. 👀

**Comment by lied** [comment]
My Integration was updated to v2.0.0b17 automatically 4 days ago and only @Rodrigolmti removal+reinstall procedure worked for me. Thanks!

**Comment by OctoNezd** [comment]
Reinstalling didnt help me. Any steps I can do to troubleshoot this? I am running 2.0.0b17 on 2025.4.1.

I get this in logs:
```
Error while executing request: Read timed out. (read timeout=3): {"did":"661229405","id":97,"data":{"did":"661229405","id":97,"method":"get_properties","params":[{"did":"0","siid":2,"piid":1},{"did":"1","siid":2,"piid":2},{"did":"2","siid":3,"piid":1},{"did":"3","siid":3,"piid":2},{"did":"4","siid":3,"piid":3},{"did":"5","siid":4,"piid":1},{"did":"6","siid":4,"piid":2},{"did":"7","siid":4,"piid":3},{"did":"8","siid":4,"piid":4},{"did":"9","siid":4,"piid":5},{"did":"10","siid":4,"piid":6},{"did":"11","siid":4,"piid":7},{"did":"15","siid":4,"piid":11},{"did":"16","siid":4,"piid":12},{"did":"18","siid":4,"piid":14}]}}
```
