### ISSUE TITLE
after update minus 30 entities and no map

### ISSUE THREAD

**Issue by eumel7** [Tasshack/dreame-vacuum#9]
Hello
sorry for my english ;-(
My Device is an "Dreame L10s_Ultra" ModelID: dreame.vacuum.r2228o
Codename: p2228
today i have updated and now i have no map anymore on all card´s after a little check and reinstallation... now i have minus ca. 30 entities (only 82). 17 entities not available, 24 de-activated

"camera.dreamebot_l10s_ultra_map" not available
"camera.dreamebot_l10s_ultra_map_data" not available
"camera.dreamebot_l10s_ultra_map_data_1" completly gone

and now is the name of my device "dreame.vacuum.r2228o"
before was the name of my device "dreame.vacuum.r2228" i think ? maybe

HA is up to date.
HACS is up to date.

any ideas ? wat i can do?
cu eumel7

**Comment by erkac** [comment]
Yes, I hit the same issue, but now after the latest update all is back in normal. Thanks!

**Comment by eumel7** [comment]
Hi 
![Vacuum entities](https://user-images.githubusercontent.com/98071666/196941429-a5a0af3e-2383-45e6-b70d-ea0cddd35128.png)
 ok now thanks
